version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    container_name: jenkins-cicd
    hostname: jenkins
    restart: always
    user: root
    ports:
      - 8083:8080
      - 50003:50000
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home: {}